### ISSUE TITLE
Error while trying to setup

### ISSUE THREAD

**Issue by Anto007** [putonti/virMine#1]
I'm new to using docker and I'm getting the below error after running sudo docker build -t virmine . I'm on Ubuntu 16.04 and I would appreciate any assistance from you in this regard

Step 11/36 : RUN git clone https://github.com/najoshi/sickle
 ---> Running in 06b159905807
Cloning into 'sickle'...
Removing intermediate container 06b159905807
 ---> 8ca4d070bf47
Step 12/36 : RUN cd sickle && make
 ---> Running in c9e53538d60d
gcc -Wall -pedantic -DVERSION=1.33 -O3 -c src/sliding.c
gcc -Wall -pedantic -DVERSION=1.33 -O3 -c src/trim_single.c
src/trim_single.c: In function 'single_main':
src/trim_single.c:85:50: warning: statement will never be executed [-Wswitch-unreachable]
             if (single_long_options[option_index].flag != 0)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
gcc -Wall -pedantic -DVERSION=1.33 -O3 -c src/trim_paired.c
src/trim_paired.c: In function 'paired_main':
src/trim_paired.c:130:50: warning: statement will never be executed [-Wswitch-unreachable]
             if (paired_long_options[option_index].flag != 0)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
gcc -Wall -pedantic -DVERSION=1.33 -O3 -c src/sickle.c
gcc -Wall -pedantic -DVERSION=1.33 -O3 -c src/print_record.c
gcc -Wall -pedantic -DVERSION=1.33  -O3 sliding.o trim_single.o trim_paired.o sickle.o print_record.o -o sickle -lz
Removing intermediate container c9e53538d60d
 ---> 454ccf629cfa
Step 13/36 : RUN cd megahit && make
 ---> Running in 49a807869085
make: *** No targets specified and no makefile found.  Stop.

**Comment by thatzopoulos** [comment]
Thank you for letting me know, I have pushed a change that should fix this.
`git pull` the repo and everything should run fine.

**Comment by Anto007** [comment]
Thank you very much. Does virMine take gzipped read flles?

**Comment by putonti** [comment]
Yes. It accepts gzipped files. The first step, read QC, will unzip them and QC them.
